### PR TITLE
UIApplicationDelegate protocol requirements regarding UIWindow as an Optional

### LINKED ISSUE #20: Emphasize UIApplicationDelegate protocol requirements
Adjust sample project to emphasize UIApplicationDelegate protocol requirements.

In the current example project window is defined as:

```
  let window = UIWindow()
```

If I am using some libraries like [SVProgressHUD](https://github.com/SVProgressHUD/SVProgressHUD) which access the current `UIWindow` via the following selector `UIApplication.shared.delegate?.window` they all crash as this invocation returns nil.

Hence, I propose to update the sample project to meet those protocol requirements.

### PR DESCRIPTION
**Pull request by benjohnde**
Closes #20

### CODE REVIEW

File: Sample/SampleDelegate/SampleDelegate/AppDelegate.swift [hunk 1]
```diff
@@ -25,7 +25,7 @@ import SuperDelegate
 @UIApplicationMain
 class AppDelegate: SuperDelegate, ApplicationLaunched {
     
-    let window = UIWindow()
+    var window: UIWindow? = UIWindow()
```
Comment (dfed) [inline Sample/SampleDelegate/SampleDelegate/AppDelegate.swift]: we'd need `window` to be `public` to solve this problem, right?

I personally _hate_ making things optional when they don't need to be. Maybe the right answer here is to only initialize `window` in `loadInterface`, since we don't really need one until we have to load our interface — we're likely using a dash more memory than we need to when apps are loaded in the background right now.

The upside of setting `window` in `loadInterface` is that we'd get rid of the `preconditionFailure`:
```
func loadInterface(launchItem: LaunchItem) {
          // Setup our main window since we don't have a storyboard.
          let window = UIWindow()
          self.window = window
          setup(mainWindow: window)
          window.rootViewController = ViewController()
```

Comment (benjohnde) [reply Sample/SampleDelegate/SampleDelegate/AppDelegate.swift]: It does not need to be `public`. If you would have the following scenario: `MyAppDelegate` inherits from `AbstractAppDelegate` which inherits from `SuperDelegate`, you would need this property to be `public`.

Comment (dfed) [reply Sample/SampleDelegate/SampleDelegate/AppDelegate.swift]: You're right re public! My first look at this I hadn't realized you were making changes in the sample project :)
